### ISSUE TITLE
decodeimage のサンプル

### ISSUE THREAD

**Issue by Reputeless** [voidproc/siv3d_examples#1]
https://gist.github.com/voidproc/21c445757ea33e5d1d2350fd72731fe0#file-decodeimage-cpp-L23 は

``` cpp
const Texture texture(Base64::Decode(encodedImage));
```

で大丈夫です。
Texture は ByteArray から画像フォーマットを推測できます。

**Comment by voidproc** [comment]
ありがとうございます。
コードを修正しました。
